version: "3.9"
services:
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssword123"
    ports:
      - "1433:1433"
  solarwatchapp2:
    image: solarwatchapp2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ENVIRONMENT=Production 
      - Authentication__IssuerSigningKey=!SuperSecretSecretKey!